### ISSUE TITLE
Conncurant Connections Is Now Limited To Just 2

### ISSUE THREAD

**Issue by Chunkford** [mrbrianevans/companies-house-stream#8]
FYI
There's been a change to the streaming API - https://forum.aws.chdev.org/t/streaming-api-concurrent-connections/4912
As your code connects to all 6 at once, it will cause problems :(

**Comment by mrbrianevans** [comment]
Hi Paul,
Thanks for letting me know. 
I have updated my code to work with this limitation that they have imposed.
What I've done is created 3 API keys on Companies House website, and then use each key for only 2 streams, and that way I can connect to all 6 at the same time.

I created a little helper class to manage the key usage to make sure I don't connect more than twice with the same key. You can see it in https://github.com/mrbrianevans/companies-house-stream/blob/master/server/src/utils/KeyHolder.ts if you're interested.

I'm running the project locally and its working again, showing events from all 6 streams.

Kind regards,
Brian

**Comment by Chunkford** [comment]
Nice one Brian I'll have a nosey later.
Hopefully using multiple keys from the same IP doesn't fall foul of their fair use policy
